import React from "react";
import Head from 'next/head'
import Landing from "../components/Landing/Landing";
import axios from "axios";


export default function Index(props) {
    const {projectsLanding} = props.dataProjects;
    const {imageLandingProjects} = props.datImageProjects;
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <Landing projectsLanding={projectsLanding} imageLandingProjects={imageLandingProjects}  />
        </>
    )
}



export async function getServerSideProps({ req, res }) {

    const landingProjects = await axios.get(`${process.env.REACT_APP_DATA_PROJECTS_LANDING}`)
    const imageProjects = await axios.get(`${process.env.REACT_APP_GET_IMAGE_PROJECT_LANDING}`)

    return {
        props: {
            dataProjects : landingProjects.data,
            datImageProjects : imageProjects.data
        },
    }

}